name: Deploy Sparse SPDS

on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Deploy
    name: Sparse SPDS deployment 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      # Sets up Java version
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          server-id: 'ossrh' # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: OSSRH_USERNAME # Env var that holds your OSSRH user name
          server-password: OSSRH_PASSWORD # Env var that holds your OSSRH user pw
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: SIGN_KEY_PASS # Env var that holds the key's passphrase
      - name: Deploy SPDS
        run: mvn -B -U clean deploy -Pdeployment -DskipTests
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USER }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PW }}

  snapshot-version:
    runs-on: ubuntu-latest
    needs: deployment
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

       # Semantic versioning
      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.1.0
        with:
          tag_prefix: ""
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
          major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
          minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
          version_format: "${major}.${minor}.${patch}"

      - name: Create branch and update to next SNAPSHOT version
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b version_${{ steps.versioning.outputs.version }}_SNAPSHOT
          mvn build-helper:parse-version versions:set -DnewVersion=\${{ steps.versioning.outputs.version }}-SNAPSHOT versions:commit
          git ls-files | grep 'pom.xml$' | xargs git add
          git commit --allow-empty -am "Update version to ${{ steps.versioning.outputs.version }}-SNAPSHOT"
          git push origin version_${{ steps.versioning.outputs.version }}_SNAPSHOT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for SNAPSHOT version
        run: |
          gh pr create -B develop -H version_${{ steps.versioning.outputs.version }}_SNAPSHOT -t "Update to next SNAPSHOT version" -b "Update to next SNAPSHOT version"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
